# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       gstreamer1.0
Summary:    GStreamer streaming media framework runtime
Version:    1.3.1
Release:    0
Group:      Applications/Multimedia
License:    LGPLv2+
URL:        http://gstreamer.freedesktop.org/
Source0:    %{name}-%{version}.tar.xz
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  check
BuildRequires:  python


%description
GStreamer is a streaming media framework, based on graphs of filters which
operate on media data. Applications using this library can do anything
from real-time sound processing to playing videos, and just about anything
else media-related.  Its plugin-based architecture means that new data
types or processing capabilities can be added simply by installing new 
plugins.



%package devel
Summary:    Development tools for GStreamer
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains the libraries and includes files necessary to develop
applications and plugins for GStreamer. If you plan to develop applications
with GStreamer, consider installing the gstreamer-devel-docs package and the
documentation packages for any plugins you intend to use.


%package devel-docs
Summary:    API reference for GStreamer
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description devel-docs
This package contains developer documentation for the GStreamer streaming
media framework.


%package tools
Summary:    Common tools and files for GStreamer streaming media framework
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}

%description tools
This package contains wrapper scripts for the command-line tools that work
with different major/minor versions of GStreamer.



%prep
%setup -q -n %{name}-%{version}/gstreamer

# >> setup
# << setup

%build
# >> build pre
export CFLAGS="-DG_DISABLE_ASSERT -DG_DISABLE_CAST_CHECKS"
# << build pre

%configure --disable-static \
    --with-package-name='Mer GStreamer package' \
    --with-package-origin='http://www.merproject.org/' \
    --disable-dependency-tracking \
    --disable-examples \
    --disable-tests \
    --disable-valgrind \
    --disable-debug \
    --disable-nls \
    --disable-loadsave \
    --disable-introspection \
    --with-buffer-alignment=pagesize

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING NEWS README RELEASE TODO
%{_libdir}/libgstreamer-1.0.so.*
%{_libdir}/libgstbase-1.0.so.*
%{_libdir}/libgstcontroller-1.0.so.*
%{_libdir}/libgstnet-1.0.so.*
%{_libdir}/libgstcheck-1.0.so.*
%dir %{_libdir}/gstreamer-1.0
%{_libdir}/gstreamer-1.0/libgstcoreelements.so
%dir %{_libexecdir}/gstreamer-1.0
%{_libexecdir}/gstreamer-1.0/gst-plugin-scanner
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%dir %{_includedir}/gstreamer-1.0
%dir %{_includedir}/gstreamer-1.0/gst
%{_includedir}/gstreamer-1.0/gst/*.h
%{_includedir}/gstreamer-1.0/gst/base
%{_includedir}/gstreamer-1.0/gst/check
%{_includedir}/gstreamer-1.0/gst/controller
%{_includedir}/gstreamer-1.0/gst/net
%{_datadir}/aclocal/gst-element-check-1.0.m4
%{_libdir}/libgstreamer-1.0.so
%{_libdir}/libgstbase-1.0.so
%{_libdir}/libgstcontroller-1.0.so
%{_libdir}/libgstnet-1.0.so
%{_libdir}/libgstcheck-1.0.so
%{_libdir}/pkgconfig/gstreamer-1.0.pc
%{_libdir}/pkgconfig/gstreamer-base-1.0.pc
%{_libdir}/pkgconfig/gstreamer-controller-1.0.pc
%{_libdir}/pkgconfig/gstreamer-check-1.0.pc
%{_libdir}/pkgconfig/gstreamer-net-1.0.pc
# << files devel

%files tools
%defattr(-,root,root,-)
# >> files tools
%{_bindir}/gst-inspect-1.0
%{_bindir}/gst-launch-1.0
%{_bindir}/gst-typefind-1.0
%doc %{_mandir}/man1/gst-inspect-1.0.*
%doc %{_mandir}/man1/gst-launch-1.0.*
%doc %{_mandir}/man1/gst-typefind-1.0.*
# << files tools
